# I. Lý thuyết (10 câu, mỗi câu 0.5 điểm)

1. Trong mô hình xác suất Naive Bayes giả định nào được đặt ra và được xem là ngây ngô (naive)? 

Đáp án: Mô hình Naive Bayes dựa trên giả định khá ngây ngô về sự độc lập có điều kiện giữa các chiều dữ liệu. Thông thường giả định này khó đạt được trên thực tế. Đặc biệt là đối với dữ liệu dạng văn bản vì các từ trong câu có sự phụ thuộc lẫn nhau.

2. Giải thích các đại lượng của công thức Bayes sau

$$P(y|x) = \frac{P(y)P(x|y)}{P(x)}$$

Đáp án:
Trong công thức trên các thành phần là:
- $P(y|x)$ là _xác suất hậu nghiệm_ (_posteriori probability_): Đây là xác suất chỉ biết được trong điều kiện đã xác định dữ liệu đầu vào $x$. 
- $P(y)$ là _xác xuất tiên nghiệm_ (_prior probability_): Xác suất dựa trên kinh nghiệm đã có từ trước và hoàn toàn không phụ thuộc vào dữ liệu. Thông thường với kích thước mẫu lớn thì xác suất này được xác định dựa vào tỷ lệ của tấn suất mẫu.
- $P(x|y)$ là _hàm hợp lý_ (_likelihood function_). Đây là xác suất của toàn bộ dữ liệu đầu vào $x$ khi đã biến trước $y$.
- $P(x)$ là phân phối xác suất của dữ liệu không phụ thuộc vào giá trị của $y$. Xác xuất này được xem như dấu hiệu (_evidence_) của dữ liệu. Xác suất tồn tại như một hằng số nhưng không dễ dàng tính được (_intractable_). Chính vì thế khi so sánh xác suất $P(y|x)$ chúng ta thường tính toán thông qua công thức đồng dạng xác suất:

$$P(y|x) \propto P(y)P(x|y)$$

Đồng dạng được hiểu là xác suất ở vế trái bằng vế phải nhân với một hằng số.

3. Phương pháp MAP tối đa hoá hàm mục tiêu là gì? Ưu điểm của MAP so với MLE là gì?

Theo phương pháp $MAP$ ta có 

$$\begin{eqnarray}\hat{\mathbf{w}} & = & \arg \max_{\mathbf{w}}~ \log P(\mathbf{w}| \mathcal{D}) \\
& = & \arg \max~ \log \frac{P(\mathcal{D}|\mathbf{w}) P(\mathbf{w})}{P(\mathcal{D})} \\
& = & \arg \max~ \underbrace{\log P(\mathcal{D}|\mathbf{w})}_{\text{log likelihood}} + \underbrace{\log P(\mathbf{w})}_{\text{prior}} - \underbrace{\log P(\mathcal{D})}_{\text{evidence}} \\
& = & \arg \max~ \log P(\mathcal{D}|\mathbf{w}) + \log P(\mathbf{w})
\end{eqnarray}$$

- Phương pháp MAP sẽ tối đa hoá hàm mục tiêu là xác suất hậu nghiệm $P(\mathbf{w}| \mathcal{D})$. Trong đó $\mathbf{w}$ là véc tơ tham số của mô hình ước lượng (_estimator_) và $\mathcal{D}$ là bộ dữ liệu đầu vào.
- Ưu điểm của phương pháp MAP đó là chúng ta có thể đưa thêm vào niềm tin của mình về mô hình thông qua xác suất tiên nghiệm $P(\mathbf{w})$ (_prior probability_) để tối đa hoá hàm mục tiêu.

4. Nếu $B_1, B_2, ..., B_n$ là một hệ đầy đủ các biến cố và $A$ với $P(A) > 0$ thì với mỗi $k=1, 2, ...n$. Hãy chứng minh 
$$P(B_k|A) = \frac{P(B_k)P(A|B_k)}{\sum_{i=1}^n P(B_i) P(A|B_i)}$$

Theo định lý `Bayes` ta có:

$$
P(A)P(B_k|A) = P(B_k)P(A|B_k)
$$ 

vì cùng bằng $P(AB_k)$.

Từ đó suy ra:
$$P(B_k|A) = \frac{P(B_k)P(A|B_k)}{P(A)}$$
Mặt khác do $\{B\}_{i=1}^n$ là một hệ đầy đủ các biến cố nên suy ra:
$$P(A) = \sum_{i=1}^n P(A, B_i) = \sum_{i=1}^{n} P(B_i)P(A|B_i)$$
Thay vào mẫu ta được công thức cần chứng minh.

Lưu ý: Công thức `Bayes` sẽ có dạng:

$$P(B_k|A) = \frac{P(B_k)P(A|B_k)}{P(A)}$$

Nếu ta khai triển mẫu của chúng thành tổng thì sẽ thu được dạng mở rộng của công thức `Bayes`:

$$P(B_k|A) = \frac{P(B_k)P(A|B_k)}{\sum_{i=1}^n P(B_i) P(A|B_i)}$$

Một người đi tới công ty làm việc sử dụng 30% lượt để đi ô tô, 30% lượt để đi bộ, và 40% lượt để đi xe bus. Biết rằng, người đó sẽ bị trễ 3% khi lái xe ô tô, 10% số lượt khi đi bộ, và 7% khi đi xe bus. 
5. Tính xác xuất để người đó đi muộn?
6. Xác suất người đó đi xe bus nếu anh ta đến muộn là bao nhiêu?
7. Tính xác suất để người đó đi bộ nếu đến đúng giờ.

- Gọi $H$ là biến cố người đó đi làm muộn, thì $\bar{H}$ là biến cố người đó đi làm đúng giờ 

- Gọi $A, B, C$ lần lượt là biến cố người đó đi làm bằng ô tô, đi bộ và đi xe bus. Thì ta có 
$$P(A) = 0.3, P(B) = 0.3, P(C) = 0.4$$

Mà người đó sẽ bị trễ 10% số lượt khi đi bộ, 3% số lượt khi lái xe ô tô và 7% số lượt khi đi xe bus nên ta có 
$$
P(H|A) = 0.03 \\
P(H|B) = 0.1 \\
P(H|C) = 0.07 \\
$$
Từ đó:

5. Xác suất để người đó đi làm muộn là 
$$\begin{eqnarray}P(H) & = & P(A)P(H|A) + P(B)P(H|B) + P(C)P(H|C) \\
& = & 0.3*0.03 + 0.3*0.1 + 0.4 * 0.07 \\
& = & 0.067
\end{eqnarray}$$

6. Xác suất người đó đi xe buýt nếu anh ta đến muộn là
$$P(C|H) = \frac{P(C) P(H|C)}{P(H)} = \frac{0.4 \times 0.07 }{0.067} = 0.418$$

7. Ta có 
$$P(\bar{H}) = 1 - P(H) = 0.933$$ 

Xác suất để người đó đến đúng giờ khi đi bộ
$$P(B|\bar{H}) = \frac{P(B)P(\bar{H}|B)}{P(\bar{H})} = \frac{0.3 \times 0.9}{0.933} = 0.289$$

8. Xác suất để một người bị bệnh lao là 0.05%, và xác suất để dương tính là với 99% độ chính xác. Tính xác suất để một người bị bệnh lao nếu người đó khi test bị dương tính. 

- Gọi $H$ là biến cố người đó dương tính với bệnh lao
- Gọi $A, B$ là lần lượt là biến cố bị bệnh và không bị bệnh  
$$P(A) = 0.0005, P(B) = 0.9995$$
$$P(H|A) = 0.99 \\
P(H|B) = 0.01
$$
Nên xác suất để một người dương tính với bệnh lao là 
$$P(H) = P(A)P(H|A) + P(B)P(H|B) = 0.0005 \times 0.99  + 0.9995 \times 0.01 = 0.01049$$

Xác suất để một người bị bệnh lao nếu người đó khi test bị dương tính
$$P(A|H) = \frac{P(A)P(H|A)}{P(H)} = \frac{0.0005 \times 0.99 }{0.01049} = 0.0472$$ 

Giả sử $Y_1, Y_2, ..., Y_n$ là các quan sát độc lập và $Y_i \sim N(\beta x_i, \sigma^2)$, trong đó $x_i, \sigma$ là các hằng số biết trước, $\beta$ là tham số chưa biết. Nhưng biết xác suất tiên nghiệm $\beta \sim N(\beta_0, \eta^2)$ và $\beta_0, \eta^2$ là các hằng số biết trước. 
9. Tìm phân bố xác suất hậu nghiệm của $\beta$ khi biết trước $y$
10. Tìm giới hạn của phân bố xác suất hậu nghiệm khi $\eta^2 \rightarrow \infty$

9. Ta có $Y_i \sim N(\beta x_i, \sigma^2)$ nên 
$$f(y_1, y_2,...y_n|\beta) = \prod_{i=1}^{n} \frac{1}{\sqrt{2\pi \sigma^2}} e^{-\frac{1}{2\sigma^2}(y_i - \beta x_i)^2} \propto e^{-\frac{1}{2\sigma^2} \sum_{i=1}^{n}(y_i - \beta x_i)^2} $$

Lại có, xác suất tiên nghiệm 
$$P(\beta) = \frac{1}{\sqrt{2\pi \eta^2}} e^{-\frac{1}{2\eta^2}(\beta - \beta_0)^2}$$

Mà công thức xác suất hậu nghiệm 
$$P(\beta|y) \propto P(\beta) P(y|\beta) \propto e^{-\frac{1}{2\sigma^2} \sum_{i=1}^{n}(y_i - \beta x_i)^2 - \frac{1}{2\eta^2}(\beta - \beta_0)^2 } = e^{- \frac12 \left( \frac{1}{\sigma^2} \sum_{i=1}^{n}(y_i - \beta x_i)^2 + \frac{1}{\eta^2}(\beta - \beta_0)^2 \right)} = e^{-\frac12 M}$$

Xét 
\begin{align*}
M &= \frac{1}{\sigma^2} \sum_{i=1}^{n}(y_i - \beta x_i)^2 + \frac{1}{\eta^2}(\beta - \beta_0)^2 \\
&= \frac{\sum y_i^2}{\sigma^2} - 2\beta \frac{\sum y_i x_i}{\sigma^2} + \beta^2\frac{\sum x_i^2}{\sigma^2} + \beta^2 \frac{1}{\eta^2} - 2\beta \frac{\beta_0}{\eta^2} + \frac{\beta_0^2}{\eta^2} \\
&= \beta^2 \underbrace{\left( \frac{\sum x_i^2}{\sigma^2} + \frac{1}{\eta^2} \right)}_{1/\sigma_1^2} - 2\beta \underbrace{\left(\frac{\sum y_i x_i}{\sigma^2} + \frac{\beta_0}{\eta^2} \right)}_{\beta_1/\sigma_1^2} + \frac{\sum y_i^2}{\sigma^2} +  \frac{\beta_0^2}{\eta^2} \\
&= \beta^2 \frac{1}{\sigma_1^2} - 2\beta \frac{\beta_1}{\sigma_1^2} + \beta_1^2\frac{1}{\sigma_1^2} + \underbrace{\frac{\sum y_i^2}{\sigma^2} +  \frac{\beta_0^2}{\eta^2} - \beta_1^2\frac{1}{\sigma_1^2}}_{C}\\
&= \frac{(\beta-\beta_1)^2}{\sigma_1^2} + C
\end{align*}
Trong đó 
$$\sigma_1^2 = \frac{1}{\frac{\sum x_i^2}{\sigma^2} + \frac{1}{\eta^2}}, \beta_1 = \sigma_1^2 \frac{\sum y_i x_i}{\sigma^2} + \frac{\beta_0}{\eta^2}$$
Như vậy phân phối xác suất hậu nghiệm $\beta|y \propto N(\beta_1, \sigma_1^2)$


10. Ta có $\eta^2 \rightarrow \infty$ thì:
$$\sigma_1^2 \rightarrow \frac{1}{\frac{\sum_{x_i^2}}{\sigma^2}} = \frac{\sigma^2}{\sum x_i^2}, \\ \beta_1 \rightarrow \frac{\sigma^2}{\sum x_i^2} \frac{\sum{y_ix_i}}{\sigma^2}= \frac{\sum y_i x_i}{\sum x_i^2}$$ 

(theo cách đặt ở cuối câu 9). Do đó 

$$\beta | y \sim N(\frac{\sum y_i x_i}{\sum x_i^2}, \frac{\sigma^2}{\sum x_i^2})$$

II. Thực hành (5 câu, mỗi câu 1 điểm)

1. Cho bộ dữ liệu về phân loại văn bản gồm các câu theo chủ để như sau:

**ẩm thực**:
```
- phở là một trong những món ăn truyền thống của Hà Nội
- hương vị của vịt quay tạo nên một vị phở đậm đà
```

**thể thao**:
```
- đội tuyển bóng đá nam đã tạo ra kì tích tại đại hội thể thao Seagame 31.
- world cup là mùa giải bóng đá lớn nhất hành tinh.
```

Hãy xây dựng mô hình `Naive Bayes` với phân phối Multinomial để phân loại các câu văn theo topic mà không sử dụng thư viện scikit-learn.



Gọi $x_i$ là từ thứ $i$ trong bộ từ điển có kích thước là $d$, $\mathbf{x}_j$ là văn bản thứ $j$. Tần suất của từ $x_i$ xuất hiện trong văn bản thứ $\mathbf{x}_j$ là $N_{ij}$. Theo công thức Bayes:

$$\begin{eqnarray}P(y=c|\mathbf{x}_j) & = & \frac{P(\mathbf{x}_j | y=c) P(y=c)}{P(\mathbf{x}_j)} \\
& \propto & \underbrace{P(y=c)}_{\text{prior}} \underbrace{\prod_{i=1}^{d} P(x_i| y=c)^{N_{ij}}}_{\text{likelihood}}
\end{eqnarray}$$

Ở đây ta có thể xem tập hợp $(N_{1j}, N_{2j}, \dots, N_{dj} )$ như là véc tơ phân phối tần suất của toàn bộ các từ trong từ điển trong văn bản $\mathbf{x}_j$

Lấy log 2 vế ta có:
$$\log P(y=c|\mathbf{x}_j) \propto \log P(y=c) + N_{ij}\sum_{i=1}^{d} \log P(x_i| y=c)$$

In [ ]:
import numpy as np

In [ ]:
sentence1 = 'phở là một trong những món ăn truyền thống của Hà Nội'
sentence2 = 'hương vị của vịt quay tạo nên một vị phở đậm đà'
sentence3 = 'đội tuyển bóng đá nam đã tạo ra kì tích tại đại hội thể thao Seagame 31'
sentence4 = 'world cup là mùa giải bóng đá lớn nhất hành tinh'

X_train = [sentence1, sentence2, sentence3, sentence4]
y_train = [0, 0, 1, 1]

In [ ]:
def process(sentence):
    '''
    split a sentence into a list
    '''
    wordList = sentence.split(' ')
    return wordList


def getFreqs(data, label):
    '''
    count frequency of each word in a label
    '''
    freqs = {}
    for sentence, label in zip(data, label):
        for word in process(sentence):
            # define key of dict
            pair = (word, label)
            # If the key exists in the dictionary, increment to 1
            if pair in freqs:
                freqs[pair] += 1        
            # else, if the key new, set equal to 1
            else:
                freqs[pair] = 1
    
    return freqs


def getNumberWords(freqs, label):
    '''
    count number of word for each label
    '''
    N = 0
    for pair, freq in freqs.items():
        if pair[1] == label:
            N += freq
    return N


def likelihood(Nci, Nc, d, alpha=1):
    '''
    Laplace smoothing formula to compute probability of word x_i belong to class c
    Input:
      Nc: a number of word in all documents of class c
      Nci: a number of word i in document i belong to class c
    Output:
      Laplace smoothing probability of word i in class c
    '''
    lmbda = (Nci + alpha) / (Nc + d * alpha)
    return lmbda 


def lookup(freqs, word, label):
    """
    Input:
        freqs: a dictionary with the frequency of each pair (or tuple)
        word: the word to look up
        label: the label corresponding to the word
    Output:
        n: the number of times the word with its corresponding label appears.
    """
    n = 0  # freqs.get((word, label), 0)
    pair = (word, label)
    if (pair in freqs):
        n = freqs[pair]
    return n


def train(X_train, y_train):
    
    # calculate p(c)
    nSample = len(y_train)
    labelList = np.unique(y_train)
    priorDict = {label: np.sum(y_train == label) / nSample for label in labelList}
    logprior = {label: np.log(prior) for label, prior in priorDict.items()}
    
    
    # calculate likelihood
    loglikelihood = {}
    freqs = getFreqs(X_train, y_train)
    vocab = set([pair[0] for pair in freqs.keys()])
    V = len(vocab)
    for label in labelList:
        # Total words of label c
        Nc = getNumberWords(freqs, label)
        for word in vocab:
            # total word x_i in label c
            Nic = lookup(freqs, word, label)
            # likelihood P(xi|y=c)^Nic
            likeli = Nic*np.log(likelihood(Nic, Nc, V))
            loglikelihood[(word, label)] = likeli
            
    return logprior, loglikelihood, vocab, freqs, labelList


# Train data
logprior, loglikelihood, vocab, freqs, labels = train(X_train, y_train)

2. Sử dụng mô hình vừa huấn luyện, hãy dự báo nhãn cho các văn bản sau:

```
các món ăn đường phố là một văn hóa truyền thống của người Việt.
```
và 

```
Quang Hải đã được mua lại bởi một đội bóng truyền thống tại Pháp.
```

In [ ]:
def predict(sentence, logprior, loglikelihood, vocab, freqs, labels):
    wordList = process(sentence)
    wordSet = set(wordList)
    
    scoreList = []
    V = len(vocab)
    for label in labels:
        p = 0
        pc = logprior[label]
        p += pc
        for word in wordSet:
            if word in vocab:
                loglikeli = loglikelihood[(word, label)]
            else: 
                Nic = 0
                Nc = getNumberWords(freqs, label)
                loglikeli = np.log(likelihood(Nic, Nc, V))
                
            p += loglikeli
        scoreList.append(p)
        
    return np.argmax(scoreList)


X_test = ['các món món ăn đường phố là một văn hóa truyền thống của người Việt', 
          'Quang Hải đã được mua lại bởi một đội bóng truyền thống tại Pháp']

for sentence in X_test:
    y_pred = predict(sentence, logprior, loglikelihood, vocab, freqs, labels)
    print(f'Sentence: {sentence} - Label: {y_pred}')

Sentence: các món món ăn đường phố là một văn hóa truyền thống của người Việt - Label: 1
Sentence: Quang Hải đã được mua lại bởi một đội bóng truyền thống tại Pháp - Label: 0


3. Xây dựng mô hình `NaiveBayes Classifier` với phân phối Gaussian để phân loại các loài hoa từ bộ dữ liệu iris mà không cần sử dụng scikit-learn. Để load bộ dữ liệu iris có thể sử dụng sklearn như sau:

```
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target
```


In [ ]:
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
# we have to compute mean/standard deviation belong to each class
# based on this to compute likelihood P(x|y=c) = f(x; mu_c, std_c)
meanList = []
stdList = []

for label in np.unique(y):
    indices = np.where(y == label)[0]
    meanList.append(X[indices, :].mean(axis=0))
    stdList.append(X[indices, :].std(axis=0))

meanList, stdList

([array([5.006, 3.428, 1.462, 0.246]),
  array([5.936, 2.77 , 4.26 , 1.326]),
  array([6.588, 2.974, 5.552, 2.026])],
 [array([0.34894699, 0.37525458, 0.17191859, 0.10432641]),
  array([0.51098337, 0.31064449, 0.46518813, 0.19576517]),
  array([0.62948868, 0.31925538, 0.54634787, 0.27188968])])


4. Dự báo đối với hai quan sát mới có giá trị 
`['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)']` lần lượt như sau:

```
[6.4, 3.1, 5.5, 1.8]
và  
[4.9, 3. , 1.4, 0.2],
```

In [ ]:
# 4
from scipy import stats

def predict(x, meanList, stdList):
    probabilities = []
    classes = len(meanList)
    for c in range(classes):
        score = stats.multivariate_normal.pdf(x, mean=meanList[c], cov=stdList[c])
        probabilities.append(score)
    return np.argmax(probabilities)

x1 = [6.4, 3.1, 5.5, 1.8]
x2 = [4.9, 3. , 1.4, 0.2]

print(predict(x1, meanList, stdList))
print(predict(x2, meanList, stdList))

2
0


5. Thực hành xây dựng lại mô hình `NaiveBayes` theo package `scikit-learn` để phân loại các loài hoa trong bộ dữ liệu iris.

In [ ]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X, y)

GaussianNB()

In [ ]:
X_test = [x1, x2]
clf.predict(X_test)

array([2, 0])